config/routes.rb
Rails.application.routes.draw do
  resources :users

  get 'admin' => 'admin#index'

  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end

  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  post 'sessions/new' => 'sessions#create'
  get 'welcome/index'

  post 'users/create' => 'users#create'

  root 'sessions#new'
  resources :users

end

app/models/building.rb
class Building < ActiveRecord::Base
end

app/models/node.rb
class Node < ActiveRecord::Base
end

app/models/path.rb
class Path < ActiveRecord::Base
end

app/models/universe.rb
class Universe < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence:true, uniqueness:true
  validates :email, presence:true, uniqueness:true
  has_secure_password
  
  def self.current_user
		Thread.current[:current_user]
	end
	
	def self.current_user=(usr)
		Thread.current[:current_user] = usr
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authorize

  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
	around_filter :set_current_user
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def set_current_user
  	User.current_user = User.find_by_id(session[:user_id])
  	yield
  ensure
  	User.current_user = nil
  end
  
  protected
  
  	def authorize
  		unless User.find_by_id(session[:user_id])
  			redirect_to root_url, notice: "Please log in"
  		end
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize

  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to welcome_index_url
    else
      redirect_to sessions_new_url, alert:"Invalid user/password combination"
    end
  end

  def destroy
  	#UserMailer.welcome_email(User.current_user).deliver
    session[:user_id] = nil
    redirect_to admin_index_url, notice:"Logged out"
  end
end

app/controllers/universes_controller.rb
class UniversesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#skip_before_filter :authorize, only: [:create, :new]
	skip_before_filter :authorize, only: [:create, :new, :show, :edit, :update, :destroy]
	skip_before_filter :verify_authenticity_token
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
		@user=User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

      	UserMailer.welcome_email(@user).deliver

        format.html { redirect_to root_url, notice: "User #{@user.name} was successfully created. Please sign in to continue." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
require './lib/map.rb'

class WelcomeController < ApplicationController
	before_filter :authorize

  def index
		#if @user.Home_Node

		@map = CampusMap.new()
		@result = [[42.365965, -71.25981]]
    name_list = Building.order(:name).pluck(:id, :name)
		adjlist = Path.pluck(:start, :end, :distance)
		@map.load_map(adjlist)
    @notes = {}
    #@notes['select default'] = nil
    name_list.sort_by{|id, name| name}.each do |id, name|
      @notes[name] = name
    end
    if params[:start] != nil && params[:end] != nil && params[:start] != '<option value=' && params[:end] != '<option value='
			@result = []
			start_id = (Building.where(name: params[:start]))[0].id.to_i
			end_id = (Building.where(name: params[:end]))[0].id.to_i
      #paths = @map.solve(params[:start].to_i, params[:end].to_i)
			paths = @map.solve(start_id, end_id)
			paths.each do |id|
				node = Node.find(id)
				@result.push([node.latitude, node.longitude])
			end
    end
  end

	#def select_home
		#building_id = params[:select_home]
		#node = Node.find(building_id)
		#node.latitude, node.longitude
	#end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/universes_helper.rb
module UniversesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<body>
<h2>Welcome to Campus GPS</h2>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Demo</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Roboto:400,100,300,500', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<%= javascript_include_tag 'jquery-1.11.1.min'%>
	<%= javascript_include_tag 'bootstrap.min'%>
	<%= javascript_include_tag 'jquery.backstretch.min'%>
	<%= javascript_include_tag 'scripts'%>
</head>

<body>
  <div class="depot_form">
			<div class="inner-bg">
				<div class="container">
					<div class="row">
						<div class="col-sm-8 col-sm-offset-2 text">
								<h1><strong>New User</strong></h1>
								<div class="description">
									<% if @user.errors.any? %>
                  <% @user.errors.full_messages.each do |message| %>
                    <p style="color: red"><%= message %></p>
                  <% end %>
									<% end %>
								</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6 col-sm-offset-3 form-box">
							<div class="form-top">
								<div class="form-top-left">
									<h3>Want to use your GPS?</h3>
										<p>Enter your username and password to log on:</p>
								</div>
							</div>
							<div class="form-bottom">
								<form role="form" action="create" class="signup-form" method="post">
									<div class="form-group">
										<label class="sr-only" for="form-username">Username</label>
										<input type="text" name="name" style="height:50px" placeholder="Username" class="form-username form-control" id="form-username">
									</div>
                  <div class="form-group">
										<label class="sr-only" for="form-email">Email</label>
										<input type="text" name="email" style="height:50px" placeholder="Email" class="form-email form-control" id="form-email">
									</div>
									<div class="form-group">
										<label class="sr-only" for="form-password">Password</label>
										<input type="password" name="password" style="height:50px" placeholder="Password" class="form-password form-control" id="form-password">
									</div>
                  <div class="form-group">
										<label class="sr-only" for="form-passwordconfirmation">Password Confirmation</label>
										<input type="password" name="password_confirmation" style="height:50px" placeholder="Password Confirmation" class="form-passwordconfirmation form-control" id="form-passwordconfirmation">
									</div>
									<button type="submit" class="btn" style="height:50px">Create</button>
								</form>
								<form action="/sessions/new">
									<button type="submit" class="btn" id="signup_button" style="height:50px">Back to login</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>







</body>
</html>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Your Information</h1>
	<% if notice %>
	<p id="notice"><%= notice %></p>
	<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<tr>
    	<td> <%= User.current_user.name %></td>
    	<td> <%= User.current_user.email %></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'Map', welcome_index_path %>
<%= link_to 'Log Out', sessions_destroy_url %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<%= javascript_include_tag 'jquery-1.11.1.min'%>
	<%= javascript_include_tag 'bootstrap.min'%>
	<%= javascript_include_tag 'jquery.backstretch.min'%>
	<%= javascript_include_tag 'scripts'%>
</head>

<body>

<%= render 'form' %>

<%= link_to 'Back to login', root_url %>
</body>
</html>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/_form.html.erb
<html lang="en" style="height: 100%">

<script src="//maps.google.com/maps/api/js?v=3.22&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<body style="height: 100%; margin: 0">
<div style='width: 100%; height: 100%;'>
  <div id="map" style='width: 100%; height: 100%;'></div>
</div>

<!-- //  handler.getMap().setZoom(15);
//  handler.getMap().setCenter(new google.maps.LatLng(42.366426, -71.258601)); -->

<script type="text/javascript">

  var anumber = 1
  var southWest = new google.maps.LatLng( 42.358631, -71.277989 );
  var northEast = new google.maps.LatLng( 42.373986, -71.243614 );
  var hyderabadBounds = new google.maps.LatLngBounds( southWest, northEast );
  var mapOptions = {
    center: new google.maps.LatLng(42.366426, -71.258601),
    maxZoom:18,
    minZoom:16,
    maxBounds: hyderabadBounds
    //scrollwheel: false,
    //zoomControl: false
  };
  var handler = Gmaps.build('Google');
     handler.buildMap({ provider: mapOptions, internal: {id: 'map'}}, function(){
       var plan = <%= raw @result %>;
       plan.options = {
         geodesic: true,
         strokeColor: '#FF0000',
         strokeOpacity: 1.0,
         strokeWeight: 4,
         title: 'plan'
       };

       function addPolyline(polyline){
         var transformedPolyline = _.map(polyline, function(coordinates){
           return { lat: coordinates[0], lng: coordinates[1] };
         })
         handler.addPolyline(transformedPolyline, polyline.options);
         handler.bounds.extend(transformedPolyline[0]);
         handler.bounds.extend(polyline[ polyline.length - 1]);
         handler.map.centerOn(map.getCenter());
       }

       if(navigator.geolocation)
          navigator.geolocation.getCurrentPosition(displayOnMap,function error(msg){alert('Please enable your GPS position future.');
}, {maximumAge:600000, timeout:8000, enableHighAccuracy: true});

       addPolyline(plan);
       handler.fitMapToBounds();
       handler.map.fitBounds(map.getMaxZoom);
       handler.getMap().setZoom(17);

       //handler.fitBounds(new google.maps.LatLngBounds( new google.maps.LatLng( 42.361897, -71.266080 ), new google.maps.LatLng( 42.370926, -71.250255 ) ));
     });

      google.maps.event.addListener(handler.getMap(), 'dragend',  function( evt ) {
        if (hyderabadBounds.contains(handler.getMap().getCenter())) return;
        handler.map.centerOn(new google.maps.LatLng(42.366426, -71.258601));
          //alert("hello!");
      });

     function displayOnMap(position){
       var marker = handler.addMarker({
         lat: position.coords.latitude,
         lng: position.coords.longitude
       });
       //handler.map.centerOn(marker);
     };
</script>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en" style="height: 100%">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Demo</title>
  <!-- <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> -->
</head>


<body>
	<nav class="navbar navbar-default" style="margin-bottom: 0">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#" style="font-size: 30px">Welcome to Campus GPS</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<form class="navbar-form navbar-left" role="search" action="/welcome/index" id="input_form">
				<div class="form-group">
          <datalist id = "building_list">
            <select>
              <%= Building.all.order(:name).each do |b| %>
              <option><%=b.name%></option>
              <%end%>
            </select>
          </datalist>
					<input name="start" type="text" class="form-control" placeholder="Start Location" list="building_list">
					<input name="end" type="text" class="form-control" placeholder="Destination" list="building_list">
				</div>
        <button type="submit" class="btn" form="input_form">Search</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
          <a class="dropdown-toggle" role="button" data-toggle="dropdown"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">page1</a></li>
          </ul>
        </li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
	</nav>

<%=render 'form', :result => @result%>

</body>